-- PECHO
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Press de banca plano barra', 'Pecho', 'Pectoral mayor en banco plano con barra'),
('Press de banca plano mancuernas', 'Pecho', 'Press plano con mancuernas'),
('Press de banca en multipower', 'Pecho', 'Press plano en máquina smith'),
('Press inclinado barra', 'Pecho', 'Énfasis en parte superior con barra'),
('Press inclinado mancuernas', 'Pecho', 'Mayor recorrido en parte superior'),
('Press inclinado en multipower', 'Pecho', 'Press inclinado guiado'),
('Press declinado barra', 'Pecho', 'Mayor énfasis en zona inferior'),
('Press declinado mancuernas', 'Pecho', 'Declinado libre con mancuernas'),
('Press declinado en multipower', 'Pecho', 'Declinado guiado'),
('Aperturas planas mancuernas', 'Pecho', 'Aislamiento con amplitud en banco plano'),
('Aperturas inclinadas mancuernas', 'Pecho', 'Aislamiento en parte superior'),
('Aperturas declinadas mancuernas', 'Pecho', 'Aislamiento en zona inferior'),
('Aperturas en peck-deck', 'Pecho', 'Máquina de aperturas'),
('Aperturas en polea alta', 'Pecho', 'Cruce desde arriba, tensión constante'),
('Aperturas en polea baja', 'Pecho', 'Cruce desde abajo hacia arriba'),
('Crossover en polea alta', 'Pecho', 'Cruce de poleas desde arriba'),
('Crossover en polea media', 'Pecho', 'Cruce a la altura del pecho'),
('Crossover en polea baja', 'Pecho', 'Cruce desde abajo'),
('Press en máquina sentado agarre neutro', 'Pecho', 'Press guiado con agarre neutro'),
('Press en máquina sentado agarre prono', 'Pecho', 'Press guiado agarre tradicional'),
('Fondos en paralelas para pecho', 'Pecho', 'Torso inclinado hacia delante'),
('Flexiones en suelo', 'Pecho', 'Autocarga en posición de plancha'),
('Flexiones declinadas', 'Pecho', 'Pies elevados para más dificultad'),
('Flexiones inclinadas', 'Pecho', 'Manos sobre banco, más fácil'),
('Flexiones en anillas', 'Pecho', 'Mayor inestabilidad'),
('Pullover con mancuerna', 'Pecho', 'Trabajo de pecho y caja torácica'),
('Pullover en polea alta', 'Pecho', 'Pullover de pie con cuerda');

-- ESPALDA
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Dominadas pronas', 'Espalda', 'Agarre prono para dorsal ancho'),
('Dominadas supinas', 'Espalda', 'Agarre supino, más bíceps'),
('Dominadas neutras', 'Espalda', 'Agarre neutro, hombros cómodos'),
('Dominadas agarre cerrado', 'Espalda', 'Mayor recorrido vertical'),
('Dominadas en anillas', 'Espalda', 'Mayor inestabilidad'),
('Jalón al pecho agarre ancho', 'Espalda', 'En polea alta'),
('Jalón al pecho agarre estrecho', 'Espalda', 'Más énfasis en dorsal medio'),
('Jalón tras nuca', 'Espalda', 'Variante clásica de jalón'),
('Jalón agarre neutro', 'Espalda', 'Agarre neutro en barra o mango'),
('Jalón con triángulo en polea', 'Espalda', 'Agarre cerrado en V'),
('Remo con barra Pendlay', 'Espalda', 'Remo explosivo desde el suelo'),
('Remo con barra estilo Yates', 'Espalda', 'Tronco más erguido'),
('Remo con mancuerna a una mano', 'Espalda', 'Remo unilateral en banco plano'),
('Remo con mancuerna pecho apoyado', 'Espalda', 'En banco inclinado'),
('Remo en barra T', 'Espalda', 'Remo con barra en T'),
('Remo en máquina Hammer', 'Espalda', 'Máquina tipo Hammer Strength'),
('Remo en polea baja agarre neutro', 'Espalda', 'Con mango neutro'),
('Remo en polea baja agarre supino', 'Espalda', 'Con agarre supino'),
('Remo en polea baja agarre prono', 'Espalda', 'Con agarre prono'),
('Remo invertido en barra', 'Espalda', 'Peso corporal bajo barra'),
('Remo invertido en TRX', 'Espalda', 'Remo con straps'),
('Pullover con mancuerna para dorsal', 'Espalda', 'Pullover enfocado en dorsal'),
('Pullover en polea de pie', 'Espalda', 'Desde polea alta al muslo'),
('Peso muerto convencional', 'Espalda', 'Trabajo global de cadena posterior'),
('Peso muerto sumo', 'Espalda', 'Apertura amplia de pies'),
('Peso muerto rumano mancuernas', 'Espalda', 'Rumano con mancuernas'),
('Peso muerto piernas rígidas barra', 'Espalda', 'Mayor estiramiento de isquios'),
('Peso muerto con trap bar', 'Espalda', 'Con barra hexagonal'),
('Remo en máquina sentado pecho apoyado', 'Espalda', 'Remo guiado con apoyo de pecho');

-- HOMBROS
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Press militar de pie barra', 'Hombros', 'Press por encima de la cabeza'),
('Press militar sentado barra', 'Hombros', 'Versión sentada con barra'),
('Press militar sentado mancuernas', 'Hombros', 'Mayor libertad de agarre'),
('Press Arnold mancuernas', 'Hombros', 'Rotación durante el press'),
('Press hombros en máquina', 'Hombros', 'Movimiento guiado'),
('Press hombros en multipower', 'Hombros', 'Press guiado en smith'),
('Press landmine a una mano', 'Hombros', 'Press diagonal con barra en esquina'),
('Elevaciones laterales mancuernas', 'Hombros', 'Deltoides lateral'),
('Elevaciones laterales en polea baja', 'Hombros', 'Tensión constante'),
('Elevaciones laterales en máquina', 'Hombros', 'Máquina específica de hombro'),
('Elevaciones frontales mancuernas', 'Hombros', 'Deltoides anterior'),
('Elevaciones frontales barra', 'Hombros', 'Barra recta al frente'),
('Elevaciones frontales en polea', 'Hombros', 'Desde polea baja al frente'),
('Pájaros mancuernas inclinado', 'Hombros', 'Deltoides posterior en banco'),
('Pájaros en peck-deck inverso', 'Hombros', 'Máquina para deltoides posterior'),
('Face pull en polea alta', 'Hombros', 'Tirón hacia la cara con cuerda'),
('Remo al mentón barra Z', 'Hombros', 'Trapecio y deltoides'),
('Remo al mentón con cuerda', 'Hombros', 'Variante en polea'),
('Y-raise mancuernas', 'Hombros', 'Elevación en Y'),
('W-raise mancuernas', 'Hombros', 'Elevación en W'),
('Press cubano mancuernas', 'Hombros', 'Rotación externa y press'),
('Rotación externa en polea', 'Hombros', 'Trabaja manguito rotador');

-- BÍCEPS
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Curl bíceps barra recta de pie', 'Bíceps', 'Curl clásico con barra'),
('Curl bíceps barra Z de pie', 'Bíceps', 'Menos tensión en muñeca'),
('Curl alterno mancuernas de pie', 'Bíceps', 'Alternando brazos de pie'),
('Curl alterno mancuernas sentado', 'Bíceps', 'Versión sentada'),
('Curl martillo mancuernas', 'Bíceps', 'Agarre neutro, braquiorradial'),
('Curl martillo en polea con cuerda', 'Bíceps', 'Variante en polea baja'),
('Curl concentrado en banco', 'Bíceps', 'Aislamiento máximo'),
('Curl en banco inclinado mancuernas', 'Bíceps', 'Mayor estiramiento'),
('Curl tipo araña en banco inclinado', 'Bíceps', 'Torso apoyado hacia delante'),
('Curl en predicador barra Z', 'Bíceps', 'Control en banco Scott'),
('Curl en predicador mancuernas', 'Bíceps', 'Unilateral en banco Scott'),
('Curl en máquina bíceps', 'Bíceps', 'Movimiento guiado'),
('Curl en polea baja barra recta', 'Bíceps', 'Tensión continua'),
('Curl en polea baja barra Z', 'Bíceps', 'Variante ergonómica'),
('Curl reverso barra Z', 'Bíceps', 'Agarre prono, más antebrazo'),
('Curl 21s barra recta', 'Bíceps', 'Parciales y completo en una serie'),
('Curl de arrastre barra', 'Bíceps', 'Barra rozando el cuerpo'),
('Curl en polea alta a una mano', 'Bíceps', 'De perfil, brazo en abducción');

-- TRÍCEPS
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Press francés barra Z tumbado', 'Tríceps', 'Extensión de codos en banco'),
('Press francés mancuernas tumbado', 'Tríceps', 'Unilateral o bilateral'),
('Press francés en polea alta con cuerda', 'Tríceps', 'Extensión sobre la cabeza'),
('Extensiones tríceps en polea agarre recto', 'Tríceps', 'Barra recta al muslo'),
('Extensiones tríceps en polea con cuerda', 'Tríceps', 'Separando al final'),
('Extensiones tríceps en polea agarre invertido', 'Tríceps', 'Agarre supino'),
('Press cerrado en banco plano', 'Tríceps', 'Press con agarre estrecho'),
('Press cerrado en multipower', 'Tríceps', 'Versión guiada'),
('Fondos en paralelas para tríceps', 'Tríceps', 'Cuerpo más vertical'),
('Fondos en banco con pies elevados', 'Tríceps', 'Mayor dificultad'),
('Patada de tríceps con mancuerna', 'Tríceps', 'En banco o de pie'),
('Patada de tríceps en polea', 'Tríceps', 'Con agarre cuerda o mango'),
('Extensión tríceps por encima de la cabeza mancuerna', 'Tríceps', 'De pie o sentado'),
('Extensión tríceps por encima de la cabeza polea', 'Tríceps', 'En polea alta'),
('Rompecráneos barra recta', 'Tríceps', 'Hacia la frente o detrás'),
('Rompecráneos barra Z', 'Tríceps', 'Versión ergonómica'),
('Press de tríceps en máquina', 'Tríceps', 'Empuje guiado'),
('Extensión de tríceps en máquina sentado', 'Tríceps', 'Extensión de codo guiada');

-- PIERNAS
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Sentadilla trasera barra alta', 'Piernas', 'Barra más alta sobre trapecio'),
('Sentadilla trasera barra baja', 'Piernas', 'Barra más baja sobre deltoides'),
('Sentadilla frontal barra', 'Piernas', 'Barra sobre la parte frontal del hombro'),
('Sentadilla goblet mancuerna', 'Piernas', 'Con mancuerna al pecho'),
('Sentadilla en multipower', 'Piernas', 'Sentadilla guiada en smith'),
('Sentadilla hack máquina', 'Piernas', 'Máquina de hack squat'),
('Sentadilla hack invertida', 'Piernas', 'De espaldas al respaldo'),
('Sentadilla sumo barra', 'Piernas', 'Apertura amplia de pies'),
('Sentadilla overhead barra', 'Piernas', 'Barra por encima de la cabeza'),
('Zancadas caminando mancuernas', 'Piernas', 'Lunges con mancuernas'),
('Zancadas caminando barra', 'Piernas', 'Lunges con barra sobre espalda'),
('Zancada búlgara mancuernas', 'Piernas', 'Pie trasero elevado'),
('Zancada búlgara barra', 'Piernas', 'Versión con barra'),
('Desplantes estáticos mancuernas', 'Piernas', 'Lunge en el sitio'),
('Desplantes atrás barra', 'Piernas', 'Lunge hacia atrás'),
('Step-up en banco mancuernas', 'Piernas', 'Subida a banco con mancuernas'),
('Step-up en cajón barra', 'Piernas', 'Subida con barra'),
('Prensa de piernas horizontal', 'Piernas', 'Prensa en plano horizontal'),
('Prensa de piernas inclinada', 'Piernas', 'Prensa a 45 grados'),
('Prensa de piernas vertical', 'Piernas', 'Prensa vertical'),
('Prensa de piernas a una pierna', 'Piernas', 'Trabajo unilateral'),
('Extensiones de cuádriceps en máquina', 'Piernas', 'Máquina de extensión de rodilla'),
('Extensiones de cuádriceps unilateral', 'Piernas', 'Una pierna cada vez'),
('Curl femoral tumbado máquina', 'Piernas', 'Curl en máquina tumbado'),
('Curl femoral sentado máquina', 'Piernas', 'Curl sentado'),
('Curl femoral de pie unilateral', 'Piernas', 'Curl de pie a una pierna'),
('Peso muerto rumano barra', 'Piernas', 'Isquios y glúteo con barra'),
('Peso muerto rumano mancuernas', 'Piernas', 'Rumano con mancuernas'),
('Peso muerto piernas rígidas barra', 'Piernas', 'Mayor estiramiento isquios'),
('Peso muerto piernas rígidas mancuernas', 'Piernas', 'Versión con mancuernas'),
('Hip thrust barra', 'Piernas', 'Cadera en banco con barra'),
('Hip thrust en máquina', 'Piernas', 'Versión guiada'),
('Puente de glúteo en suelo', 'Piernas', 'Elevación de cadera en suelo'),
('Puente de glúteo con barra', 'Piernas', 'Variante cargada en suelo'),
('Patada de glúteo en polea', 'Piernas', 'Extensión de cadera en polea baja'),
('Patada de glúteo en máquina', 'Piernas', 'Máquina específica de glúteo'),
('Abducciones de cadera en máquina', 'Piernas', 'Separar las piernas sentado'),
('Abducciones de cadera en polea', 'Piernas', 'Con tobillera en polea'),
('Aducciones de cadera en máquina', 'Piernas', 'Juntar las piernas sentado'),
('Elevación de talones de pie en máquina', 'Piernas', 'Gemelos de pie guiado'),
('Elevación de talones de pie con barra', 'Piernas', 'Gemelos con barra sobre espalda'),
('Elevación de talones sentado máquina', 'Piernas', 'Trabaja sóleo'),
('Gemelos en prensa de piernas', 'Piernas', 'Empuje de puntillas en prensa'),
('Gemelos en escalón con mancuernas', 'Piernas', 'Subida de talones en escalón'),
('Gemelos a una pierna en escalón', 'Piernas', 'Trabajo unilateral de gemelo');

-- ABDOMEN
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Crunch en suelo', 'Abdomen', 'Encogimiento básico'),
('Crunch en máquina abdominal', 'Abdomen', 'Movimiento guiado'),
('Crunch en polea alta', 'Abdomen', 'De rodillas con cuerda'),
('Crunch inverso en banco', 'Abdomen', 'Elevar cadera hacia el pecho'),
('Crunch en fitball', 'Abdomen', 'Sobre pelota suiza'),
('Crunch bicicleta', 'Abdomen', 'Alternando codo y rodilla'),
('Elevación de piernas colgado', 'Abdomen', 'Piernas extendidas'),
('Elevación de rodillas colgado', 'Abdomen', 'Rodillas flexionadas'),
('Elevación de piernas tumbado', 'Abdomen', 'En banco o suelo'),
('Elevación de piernas en banco inclinado', 'Abdomen', 'Mayor dificultad'),
('Encogimientos laterales con mancuerna', 'Abdomen', 'Trabajo de oblicuos de pie'),
('Encogimientos en banco declinado', 'Abdomen', 'Crunch en declinado');

-- CORE
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Plancha frontal en suelo', 'Core', 'Apoyo en antebrazos'),
('Plancha frontal con apoyo en banco', 'Core', 'Más fácil, sobre banco'),
('Plancha lateral en suelo', 'Core', 'Apoyo lateral en antebrazo'),
('Plancha lateral con apoyo en banco', 'Core', 'Versión más sencilla'),
('Plancha con brazos extendidos', 'Core', 'En posición de flexión'),
('Plancha con peso sobre espalda', 'Core', 'Lastre adicional'),
('Rueda abdominal desde rodillas', 'Core', 'Con rueda y apoyo en rodillas'),
('Rueda abdominal desde pies', 'Core', 'Versión avanzada'),
('Pallof press en polea', 'Core', 'Antirrotación de tronco'),
('Paseo del granjero con mancuernas', 'Core', 'Caminar cargando mancuernas a los lados');

-- ANTEBRAZO
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Curl de muñeca barra sentado', 'Antebrazo', 'Flexores de muñeca'),
('Curl de muñeca inverso barra', 'Antebrazo', 'Extensores de muñeca'),
('Curl de muñeca mancuernas', 'Antebrazo', 'Versión unilateral'),
('Curl de muñeca en banco prono', 'Antebrazo', 'Antebrazo apoyado, palma abajo'),
('Extensión de muñeca en polea', 'Antebrazo', 'En polea baja'),
('Extensión de muñeca mancuernas', 'Antebrazo', 'Mancuernas en agarre prono'),
('Farmer walk con mancuernas', 'Antebrazo', 'Paseo pesado con mancuernas'),
('Farmer walk con trap bar', 'Antebrazo', 'Paseo con barra hexagonal');

-- TRAPECIO
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Encogimientos con barra de pie', 'Trapecio', 'Barra en frente o detrás'),
('Encogimientos con mancuernas de pie', 'Trapecio', 'Mancuernas a los lados'),
('Encogimientos en multipower', 'Trapecio', 'Encogimientos guiados'),
('Encogimientos en máquina', 'Trapecio', 'Máquina específica de trapecio'),
('Encogimientos con trap bar', 'Trapecio', 'Agarre neutro y estable'),
('Remo al mentón barra recta', 'Trapecio', 'Tirón vertical'),
('Remo al mentón en multipower', 'Trapecio', 'Versión guiada'),
('Tirón a la cara con cuerda', 'Trapecio', 'Face pull alto para trapecio medio');

-- LUMBAR
INSERT IGNORE INTO ejercicios (nombre, grupo_muscular, descripcion) VALUES
('Hiperextensiones en banco lumbar', 'Lumbar', 'Extensión de tronco en banco romano'),
('Hiperextensiones en máquina lumbar', 'Lumbar', 'Máquina específica de lumbar'),
('Buenos días con barra', 'Lumbar', 'Bisagra de cadera con barra'),
('Buenos días con mancuernas', 'Lumbar', 'Bisagra con mancuernas'),
('Peso muerto desde bloques', 'Lumbar', 'Barra elevada para rango parcial'),
('Peso muerto con mancuernas', 'Lumbar', 'Versión con mancuernas'),
('Superman en colchoneta', 'Lumbar', 'Elevación simultánea de brazos y piernas');